### ISSUE TITLE
PA Review: Hosting on Heroku

### ISSUE THREAD

**Issue by tocarevmax** [tocarevmax/DrumKick#2]
- [x] Create Account
- [x] Host

**Comment by tocarevmax** [comment]
- [ ] Hosting!

**Comment by tocarevmax** [comment]
https://drumkick.herokuapp.com

**Comment by ajansel** [comment]
Great work, this is satisfactory for now! On Friday, before you make your final push, don't forget to check for minified warnings, mixed content, debuggers, console logs, etc. The console should be empty at all times on Friday.
