### ISSUE TITLE
PA Review: Search & Seed

### ISSUE THREAD

**Issue by tocarevmax** [tocarevmax/DrumKick#3]
- [x] Users can search for their favorite artists
- [x] Artists table to be seeded using real-life data fetched from Ticketmaster API.
- [x] Adequate styling
- [x] Smooth, bug-free navigation

**Comment by ajansel** [comment]
This looks incredible! Great work! My only feedback is: 
- When I hit enter, it seems to do a different search than normal. For example if I start trying to search for 'kayne' and only have 'ka' in the search bar it returns the correct results but when I hit enter it changes the results (originally when we talked last I thought it was just a different order but it seems to be showing completely different results, in this case with 'ka' typed in, the wrong results. 

Other than that, looks great! Excellent job with your seed data too, it had everyone I thought of searching for!

**Comment by ajansel** [comment]
Again, once this is fixed I can close the issue

**Comment by tocarevmax** [comment]
I've just fixed this bug with 'enter' returning different search result. I was not keying into this.state properly, it should work now. :)

**Comment by tocarevmax** [comment]
pushing to heroku now.

**Comment by ajansel** [comment]
Awesome, good work! I just checked it, seems fine now!

**Comment by ajansel** [comment]
One more thing I just noticed. When I click outside the search bar, hit enter, navigate to a different page, etc. the search input should clear.

**Comment by tocarevmax** [comment]
- The input field should clear now

- I have also made it so the search component goes away if a person starts typing in the search field and then deletes all characters.

**Comment by ajansel** [comment]
Awesome, good work! I see the input field clearing, looks great. I really like that it goes away when they delete all the characters. One thing that I noticed is that the two behave slightly different. When they click outside the search box, the state clears, but the search results are still on the screen (which is different than how it works when they delete the characters and the input clears). Is this intended? Or do you think you should also close the search results if they click outside of it? 

Let me know if that doesn't make sense.

**Comment by tocarevmax** [comment]
Hi AJ, yes, this is intentional.

With the input field clearing: a user may start typing something, see search result of interest, click out of the input field and scroll through search results without component going away.

With search component going away on characters being deleted: the intended use is that a user may start typing something in the search field, that will mean that whatever page they were on will get overwritten with search component. They may realize that they don't want to do that and get back to their previous page easily. They can simply delete all the characters or press an "X" for the search component to go away. 

Let me know if that clarifies. Cheers.

**Comment by ajansel** [comment]
Yep, that does! Sounds great. Just wanted to be sure to point out anything you might have missed! This looks great!
