### ISSUE TITLE
PA Review: View & Track Artist

### ISSUE THREAD

**Issue by tocarevmax** [tocarevmax/DrumKick#4]
- [x] Users are able to track their favorite artists, triggering user-artist association pushed to the database
- [x] Users can see detailed information on each found artist and all of their upcoming concerts
- [x] Adequate styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds to demonstrate the feature

**Comment by tocarevmax** [comment]
I start working on tracking an artist and user dashboard today.

**Comment by ajansel** [comment]
This seems to be working great! Some thoughts: 
- Should you also display the concert name/title when listing them on the artist show page? 
- Otherwise, it looks good! I'll do a deeper look when I can see this reflected in the user feed!

**Comment by tocarevmax** [comment]
- I have added concert title to the list of concerts on Artist detail page.

**Comment by ajansel** [comment]
Looks great! I think this is a nice added touch! If you think otherwise, no pressure keeping it this way!
