### ISSUE TITLE
PA Review: View Concert Details

### ISSUE THREAD

**Issue by tocarevmax** [tocarevmax/DrumKick#5]
- [x] Users are able to view detailed information on specific concerts of interest.
- [x] Concert table to be seeded using real-life data fetched from Ticketmaster API.
- [x] Adequate styling
- [x] Smooth, bug-free navigation

**Comment by ajansel** [comment]
Things are looking incredible!! Great work! A couple of thoughts: 
- When I hover over the 'SF Bay Area Concerts' tab and click on one of them, it goes to the new page but it does not close the drop down, but it should. That way the user doesn't have to move their mouse to get it to go away. 
- Additionally, it seems that the concert pictures do not match the concert name. For example it looks like Taylor Swift is the picture for the second concert in the left column but the name is '99.7 NOW! Presents POPTOPIA'. Also, when I click on that link, it goes to the show page and has her picture, that title, but then the artist says 'Ed Sheeran'. Just double check that all of this is lined up how you intend. 
- As far as the layout, look and feel, etc. The concert show (detail) pages look great!

**Comment by tocarevmax** [comment]
Thanks for the great feedback AJ!

- For the concerts dropdown not disappearing after click - I would certainly love to learn how to do it. CSS is what controls it, so I am not sure if CSS keeps track of location url change. As of now, it will go away on hover off. 

- As mentioned earlier, it is a matter of ticketmaster's seed data. Right now I have one concert - one artist connection. This is why, there could be a mismatch of concert image_url and artist image_url when one concerts has multiple artists. I have done some tweaking and haven't noticed entries that are very confusing. I could look into it more if the problem persists.

- Thanks for the compliments!

**Comment by ajansel** [comment]
No problem! 

- For the CSS, what you could do is create an event listener on hover for the element in your nav bar. And then each anchor tag in the dropdown would have an event listener on click which would remove that class. You could wait until you finish up other feedback / MVPs to try to tackle this. 
- Sounds good! I think this is totally fine given the way Ticketmaster sets this up. 

No problem!
